name: CI/CD docker

on:
  push:
    branches:
      - main

env:
  REGISTRY: registry.nocturlab.fr
  IMAGE_NAME: jc1932/brief21
  REMOTE_DIR: /var/home/jaudebert

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Build Docker image
      run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} .

    - name: Push Docker image
      run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Upload docker-compose.yml to server
      uses: appleboy/scp-action@v0.0.1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "docker-compose.yml"
        target: "${{ env.REMOTE_DIR }}"

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd ${{ env.REMOTE_DIR }}
          docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker compose down
          docker compose up -d
